
export const usaStatesListAllData = [
		{"name": "Select state", "number": "000"},
		{"name": "Alabama", "number": "001"},
		{"name": "Alaska", "number": "002"},
		{"name": "Arizona", "number": "003"},
		{"name": "Arkansas", "number": "004"},
		{"name": "California", "number": "005"},
		{"name": "Colorado", "number": "006"},
		{"name": "Connecticut", "number": "007"},
		{"name": "Delaware", "number": "008"},
		{"name": "Florida", "number": "009"},
		{"name": "Georgia", "number": "010"},
		{"name": "Hawaii", "number": "011"},
		{"name": "Idaho", "number": "012"},
		{"name": "Illinois", "number": "013"},
		{"name": "Indiana", "number": "014"},
		{"name": "Iowa", "number": "015"},
		{"name": "Kansas", "number": "016"},
		{"name": "Kentucky", "number": "017"},
		{"name": "Louisiana", "number": "018"},
		{"name": "Maine", "number": "019"},
		{"name": "Maryland", "number": "020"},
		{"name": "Massachusetts", "number": "021"},
		{"name": "Michigan", "number": "022"},
		{"name": "Minnesota", "number": "023"},
		{"name": "Mississippi", "number": "024"},
		{"name": "Missouri", "number": "025"},
		{"name": "Montana", "number": "026"},
		{"name": "Nebraska", "number": "027"},
		{"name": "Nevada", "number": "028"},
		{"name": "New Hampshire", "number": "029"},
		{"name": "New Jersey", "number": "030"},
		{"name": "New Mexico", "number": "031"},
		{"name": "New York", "number": "032"},
		{"name": "North Carolina", "number": "033"},
		{"name": "North Dakota", "number": "034"},
		{"name": "Ohio", "number": "035"},
		{"name": "Oklahoma", "number": "036"},
		{"name": "Oregon", "number": "037"},
		{"name": "Pennsylvania", "number": "038"},
		{"name": "Rhode Island", "number": "039"},
		{"name": "South Carolina", "number": "040"},
		{"name": "South Dakota", "number": "041"},
		{"name": "Tennessee", "number": "042"},
		{"name": "Texas", "number": "043"},
		{"name": "Utah", "number": "044"},
		{"name": "Vermont", "number": "045"},
		{"name": "Virginia", "number": "046"},
		{"name": "Washington", "number": "047"},
		{"name": "West Virginia", "number": "048"},
		{"name": "Wisconsin", "number": "049"},
		{"name": "Wyoming", "number": "050"},
		{"name": "Washington D.C.", "number": "051"},
	];

